server:
  port: 8765
spring:
  application:
    name: service-feign
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#feign自带hystric 默认关闭
feign:
  hystrix:
    enabled: true